name: Build and Deploy FleaMarket FrontEnd

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-deploy:
    runs-on: [self-hosted, windows]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore src/FleaMarket/FleaMarket.FrontEnd/FleaMarket.FrontEnd.csproj

      - name: Publish
        run: dotnet publish src/FleaMarket/FleaMarket.FrontEnd/FleaMarket.FrontEnd.csproj -c Release -o publish

      - name: Deploy to IIS folder
        shell: powershell
        run: |
          $destination = 'C:\inetpub\wwwroot\fleamarket'
          if (Test-Path $destination) {
            Remove-Item "$destination\*" -Recurse -Force
          } else {
            New-Item -ItemType Directory -Path $destination | Out-Null
          }
          Copy-Item -Path publish\* -Destination $destination -Recurse
