name: Build and Deploy FleaMarket FrontEnd

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-deploy:
    runs-on: [self-hosted, windows]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore src/FleaMarket/FleaMarket.FrontEnd/FleaMarket.FrontEnd.csproj

      - name: Publish
        run: dotnet publish src/FleaMarket/FleaMarket.FrontEnd/FleaMarket.FrontEnd.csproj -c Release -o publish

      # 1) Stop IIS app-pool and site so files aren’t locked
      - name: Stop IIS site & app-pool
        shell: powershell
        run: |
          Import-Module WebAdministration
          if (Test-Path IIS:\AppPools\fleamarket) {
            Write-Host "Stopping app-pool 'fleamarket'…"
            Stop-WebAppPool -Name 'fleamarket'
          }
          if (Test-Path IIS:\Sites\fleamarket.adrianilewicz.com) {
            Write-Host "Stopping site 'FleaMarket'…"
            Stop-Website -Name 'fleamarket.adrianilewicz.com'
          }

      # 2) Clean out the folder, ignoring any access-denied errors
      - name: Clean destination folder
        shell: powershell
        run: |
          $destination = 'C:\inetpub\wwwroot\fleamarket'
          if (Test-Path $destination) {
            Write-Host "Removing existing files…"
            Remove-Item "$destination\*" -Recurse -Force -ErrorAction SilentlyContinue
          } else {
            Write-Host "Creating folder $destination…"
            New-Item -ItemType Directory -Path $destination | Out-Null
          }

      # 3) Copy in the new publish output
      - name: Deploy to IIS folder
        shell: powershell
        run: |
          $destination = 'C:\inetpub\wwwroot\fleamarket'
          Write-Host "Copying published files…"
          Copy-Item -Path publish\* -Destination $destination -Recurse -Force

      # 4) Restart site & app-pool
      - name: Start IIS site & app-pool
        shell: powershell
        run: |
          Import-Module WebAdministration
          Write-Host "Starting app-pool 'fleamarket'…"
          Start-WebAppPool -Name 'fleamarket'
          Write-Host "Starting site 'FleaMarket'…"
          Start-Website -Name 'fleamarket.adrianilewicz.com'
